# -*- coding: utf-8 -*-
"""Task-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LlZeFP7jBiq6HoWl-xlJebWtZ-UeYBSL
"""

import pandas as pd
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Create sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Sales': [2500, 1500, 3000],
    'Region': ['North', 'South', 'East']
}

df = pd.DataFrame(data)

# Generate report
report_file = 'sales_report.html'
df.to_html(report_file, index=False)

# Function to send email
def send_email(report_file):
    sender_email = 'your_email@example.com'
    receiver_email = 'recipient@example.com'
    password = 'your_password'

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = receiver_email
    msg['Subject'] = 'Automated Sales Report'

    with open(report_file, 'r') as file:
        report_content = file.read()

    msg.attach(MIMEText(report_content, 'html'))

    try:
        with smtplib.SMTP('smtp.example.com', 587) as server:
            server.starttls()
            server.login(sender_email, password)
            server.send_message(msg)
            print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")

# Call the function to send the email
send_email(report_file)

from google.colab import drive
drive.mount('/content/drive')